# Generated by Django 2.2.5 on 2019-11-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppIADS', '0003_auto_20191002_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
