# Generated by Django 2.2.5 on 2019-12-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppIADS', '0007_auto_20191204_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_imamge'),
        ),
        migrations.AlterField(
            model_name='member',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, related_name='bb', to='MyAppIADS.Book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(related_name='orderbooks', to='MyAppIADS.Book'),
        ),
    ]
